// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: cambio/regulatorio/v1/cambio.proto

package regulatoriov1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RoteadorFiscalService_ValidarERotearTransacao_FullMethodName = "/cambio.regulatorio.v1.RoteadorFiscalService/ValidarERotearTransacao"
)

// RoteadorFiscalServiceClient is the client API for RoteadorFiscalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// O primeiro diálogo inteligente da API estruturado sob o padrão rigoroso
type RoteadorFiscalServiceClient interface {
	// Alterado para PascalCase puro sem sublinhado
	ValidarERotearTransacao(ctx context.Context, in *ValidarERotearTransacaoRequest, opts ...grpc.CallOption) (*ValidarERotearTransacaoResponse, error)
}

type roteadorFiscalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRoteadorFiscalServiceClient(cc grpc.ClientConnInterface) RoteadorFiscalServiceClient {
	return &roteadorFiscalServiceClient{cc}
}

func (c *roteadorFiscalServiceClient) ValidarERotearTransacao(ctx context.Context, in *ValidarERotearTransacaoRequest, opts ...grpc.CallOption) (*ValidarERotearTransacaoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidarERotearTransacaoResponse)
	err := c.cc.Invoke(ctx, RoteadorFiscalService_ValidarERotearTransacao_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RoteadorFiscalServiceServer is the server API for RoteadorFiscalService service.
// All implementations must embed UnimplementedRoteadorFiscalServiceServer
// for forward compatibility.
//
// O primeiro diálogo inteligente da API estruturado sob o padrão rigoroso
type RoteadorFiscalServiceServer interface {
	// Alterado para PascalCase puro sem sublinhado
	ValidarERotearTransacao(context.Context, *ValidarERotearTransacaoRequest) (*ValidarERotearTransacaoResponse, error)
	mustEmbedUnimplementedRoteadorFiscalServiceServer()
}

// UnimplementedRoteadorFiscalServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRoteadorFiscalServiceServer struct{}

func (UnimplementedRoteadorFiscalServiceServer) ValidarERotearTransacao(context.Context, *ValidarERotearTransacaoRequest) (*ValidarERotearTransacaoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidarERotearTransacao not implemented")
}
func (UnimplementedRoteadorFiscalServiceServer) mustEmbedUnimplementedRoteadorFiscalServiceServer() {}
func (UnimplementedRoteadorFiscalServiceServer) testEmbeddedByValue()                               {}

// UnsafeRoteadorFiscalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RoteadorFiscalServiceServer will
// result in compilation errors.
type UnsafeRoteadorFiscalServiceServer interface {
	mustEmbedUnimplementedRoteadorFiscalServiceServer()
}

func RegisterRoteadorFiscalServiceServer(s grpc.ServiceRegistrar, srv RoteadorFiscalServiceServer) {
	// If the following call panics, it indicates UnimplementedRoteadorFiscalServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RoteadorFiscalService_ServiceDesc, srv)
}

func _RoteadorFiscalService_ValidarERotearTransacao_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidarERotearTransacaoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoteadorFiscalServiceServer).ValidarERotearTransacao(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoteadorFiscalService_ValidarERotearTransacao_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoteadorFiscalServiceServer).ValidarERotearTransacao(ctx, req.(*ValidarERotearTransacaoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RoteadorFiscalService_ServiceDesc is the grpc.ServiceDesc for RoteadorFiscalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RoteadorFiscalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cambio.regulatorio.v1.RoteadorFiscalService",
	HandlerType: (*RoteadorFiscalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidarERotearTransacao",
			Handler:    _RoteadorFiscalService_ValidarERotearTransacao_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cambio/regulatorio/v1/cambio.proto",
}
